<a href="https://colab.research.google.com/github/Haila-Abdullah/NPY-sudoku-solver-numpy/blob/master/1_Sudoku_Board.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Project - Part 1: The Sudoku Board

This is the first part of our Numpy project. This project is about playing Sudoku with Numpy. Sounds like fun, right? 😃

This first part will focus on array creation and the structure of the game: the board.

In [1]:
import numpy as np

We'll use the following board as an example:

<img src="https://user-images.githubusercontent.com/872296/68136001-49d21400-ff03-11e9-8750-acb846e23046.png" width="600px">

We'll create boards from strings, as follows:

In [2]:
puzzle_str = """
020080050
400006800
600453970
000002090
004000600
010300000
057134009
009600005
030020080
"""

This is already solved, there's nothing to do here, but if you have a second, please try reading and understanding what this line does:

In [3]:
[list(line.strip()) for line in puzzle_str.split('\n') if line.strip()]


[['0', '2', '0', '0', '8', '0', '0', '5', '0'],
 ['4', '0', '0', '0', '0', '6', '8', '0', '0'],
 ['6', '0', '0', '4', '5', '3', '9', '7', '0'],
 ['0', '0', '0', '0', '0', '2', '0', '9', '0'],
 ['0', '0', '4', '0', '0', '0', '6', '0', '0'],
 ['0', '1', '0', '3', '0', '0', '0', '0', '0'],
 ['0', '5', '7', '1', '3', '4', '0', '0', '9'],
 ['0', '0', '9', '6', '0', '0', '0', '0', '5'],
 ['0', '3', '0', '0', '2', '0', '0', '8', '0']]

As any meaningful code we create and find useful, we'll try refactoring it into its own reusable function:

In [6]:
def string_puzzle_to_arr(puzzle):
    return np.array([list(line.strip()) for line in puzzle.split('\n') if line.strip()], dtype=int)

In [7]:
puzzle = string_puzzle_to_arr(puzzle_str)
puzzle

array([[0, 2, 0, 0, 8, 0, 0, 5, 0],
       [4, 0, 0, 0, 0, 6, 8, 0, 0],
       [6, 0, 0, 4, 5, 3, 9, 7, 0],
       [0, 0, 0, 0, 0, 2, 0, 9, 0],
       [0, 0, 4, 0, 0, 0, 6, 0, 0],
       [0, 1, 0, 3, 0, 0, 0, 0, 0],
       [0, 5, 7, 1, 3, 4, 0, 0, 9],
       [0, 0, 9, 6, 0, 0, 0, 0, 5],
       [0, 3, 0, 0, 2, 0, 0, 8, 0]])

👆 you can use this `puzzle` variable to practice before moving to the actual assignment:
* get rows
* get columns
* get _blocks_ (3x3 squares)


<img width="452" src="https://user-images.githubusercontent.com/872296/68136806-a3870e00-ff04-11e9-87d4-489485501fa3.png">

#### Getting a row

Rows and columns are 0-indexed, as other Python collections. That means that the _third_ row (or column) is actually index `2`. Practice here how to get the row with index `2`, you should get:

In [8]:
# Solution
third_row = puzzle[2]

expected:

In [9]:
assert np.array_equal(third_row, np.array([6, 0, 0, 4, 5, 3, 9, 7, 0]))

#### Getting a column

Columns are also 0-indexed. Practice here how to get the _5th_ column, which is index `4`, you should get:

In [10]:
# Solution
fifth_col = puzzle[:, 4]

# Alternative
fifth_col = puzzle.T[4]

In [11]:
assert np.array_equal(fifth_col, np.array([8, 0, 5, 0, 0, 0, 3, 0, 2]))

#### Getting a column

Blocks are 3x3 squares with 9 numbers, which by sudoku rules, can't contain repeated numbers, refresher image again:

<img width="452" src="https://user-images.githubusercontent.com/872296/68136806-a3870e00-ff04-11e9-87d4-489485501fa3.png">

We'll be referencing blocks by 2 indices, the first one vertically (top-bottom), the second one horizontally (left-right).

The special characteristic of a block, is that it'll be a matrix, not a vector (2 dimensional, 3x3 matrix).

For example, block `(2, 2)` is:

In [12]:
np.array([
    [0, 0, 9],
    [0, 0, 5],
    [0, 8, 0]
])

array([[0, 0, 9],
       [0, 0, 5],
       [0, 8, 0]])

And block `(0, 1)` is:

In [13]:
np.array([
    [0, 8, 0],
    [0, 0, 6],
    [4, 5, 3]
])

array([[0, 8, 0],
       [0, 0, 6],
       [4, 5, 3]])

Time to practice, your task is to extract the block `(1, 2)`:

In [14]:
# Solution
block_1_2 = puzzle[3:6, 6:9]

In [15]:
expected_block = np.array([
    [0, 9, 0],
    [6, 0, 0],
    [0, 0, 0]
])

In [16]:
assert np.array_equal(block_1_2, expected_block)

### Iterating the board

We'll implement now 3 methods that will be useful later:

* `iter_rows()`
* `iter_columns()`
* `iter_blocks()`

These methods are extremely simple, they'll just return a list of all the rows/columns/blocks to be used later. For example, I'll start providing the code to iterate all the rows in the board:

In [17]:
for row in puzzle:
    print(f"Row: {row}")

Row: [0 2 0 0 8 0 0 5 0]
Row: [4 0 0 0 0 6 8 0 0]
Row: [6 0 0 4 5 3 9 7 0]
Row: [0 0 0 0 0 2 0 9 0]
Row: [0 0 4 0 0 0 6 0 0]
Row: [0 1 0 3 0 0 0 0 0]
Row: [0 5 7 1 3 4 0 0 9]
Row: [0 0 9 6 0 0 0 0 5]
Row: [0 3 0 0 2 0 0 8 0]


Now it's your turn:

##### a) Iterate over the columns:

In [18]:
# Solution
for col in puzzle.T:
    print(f"Column: {col}")

Column: [0 4 6 0 0 0 0 0 0]
Column: [2 0 0 0 0 1 5 0 3]
Column: [0 0 0 0 4 0 7 9 0]
Column: [0 0 4 0 0 3 1 6 0]
Column: [8 0 5 0 0 0 3 0 2]
Column: [0 6 3 2 0 0 4 0 0]
Column: [0 8 9 0 6 0 0 0 0]
Column: [5 0 7 9 0 0 0 0 8]
Column: [0 0 0 0 0 0 9 5 0]


##### b) Iterate over the blocks:

In [19]:
# Solution
for pos_1 in range(3):
    for pos_2 in range(3):
        block = puzzle[(pos_1 * 3): ((pos_1+1) * 3), (pos_2 * 3): ((pos_2+1) * 3)]
        print(f"Block ({pos_1}, {pos_2}):\n{block}")

Block (0, 0):
[[0 2 0]
 [4 0 0]
 [6 0 0]]
Block (0, 1):
[[0 8 0]
 [0 0 6]
 [4 5 3]]
Block (0, 2):
[[0 5 0]
 [8 0 0]
 [9 7 0]]
Block (1, 0):
[[0 0 0]
 [0 0 4]
 [0 1 0]]
Block (1, 1):
[[0 0 2]
 [0 0 0]
 [3 0 0]]
Block (1, 2):
[[0 9 0]
 [6 0 0]
 [0 0 0]]
Block (2, 0):
[[0 5 7]
 [0 0 9]
 [0 3 0]]
Block (2, 1):
[[1 3 4]
 [6 0 0]
 [0 2 0]]
Block (2, 2):
[[0 0 9]
 [0 0 5]
 [0 8 0]]


## Time to test your code

It's finally time to test your code. We'll use an OOP approach for our board. Here you'll find the `Board` class with empty methods. We'll provide some tests in the notebook, but your job will be to move your `Board` class to the file `sudoku.py` once it's ready. Let's get started:

In [20]:
#### Solution ####
class Board:
    def __init__(self, puzzle):
        if type(puzzle) == str:
            puzzle = string_puzzle_to_arr(puzzle)
        self.arr = puzzle

    def get_row(self, row_index):
        return self.arr[row_index]

    def get_column(self, col_index):
        return self.arr[:, col_index]

    def get_block(self, pos_1, pos_2):
        return self.arr[(pos_1 * 3): ((pos_1+1) * 3), (pos_2 * 3): ((pos_2+1) * 3)]

    def iter_rows(self):
        return [row for row in self.arr]


    def iter_columns(self):
        return [col for col in self.arr.T]

    def iter_blocks(self):
        return [self.arr[(pos_1 * 3): ((pos_1+1) * 3), (pos_2 * 3): ((pos_2+1) * 3)] for pos_1 in range(3) for pos_2 in range(3)]
        # Simplified version for reading purposes:
        # result = []
        # for pos_1 in range(3):
        #     for pos_2 in range(3):
        #         block = self.arr[(pos_1 * 3): ((pos_1+1) * 3), (pos_2 * 3): ((pos_2+1) * 3)]
        #         result.append(block)

##### 1) Test: creating boards

There are two ways of creating `Board`s: 1) from strings 2) from other Numpy arrays. Let's test that they both work:

In [21]:
puzzle_str = """
020080050
400006800
600453970
000002090
004000600
010300000
057134009
009600005
030020080
"""

In [22]:
board = Board(puzzle_str)

In [23]:
expected = np.array([
    [0, 2, 0, 0, 8, 0, 0, 5, 0],
    [4, 0, 0, 0, 0, 6, 8, 0, 0],
    [6, 0, 0, 4, 5, 3, 9, 7, 0],
    [0, 0, 0, 0, 0, 2, 0, 9, 0],
    [0, 0, 4, 0, 0, 0, 6, 0, 0],
    [0, 1, 0, 3, 0, 0, 0, 0, 0],
    [0, 5, 7, 1, 3, 4, 0, 0, 9],
    [0, 0, 9, 6, 0, 0, 0, 0, 5],
    [0, 3, 0, 0, 2, 0, 0, 8, 0]
])

In [24]:
assert np.array_equal(board.arr, expected)

In [25]:
board = Board(np.array([
    [0, 2, 0, 0, 8, 0, 0, 5, 0],
    [4, 0, 0, 0, 0, 6, 8, 0, 0],
    [6, 0, 0, 4, 5, 3, 9, 7, 0],
    [0, 0, 0, 0, 0, 2, 0, 9, 0],
    [0, 0, 4, 0, 0, 0, 6, 0, 0],
    [0, 1, 0, 3, 0, 0, 0, 0, 0],
    [0, 5, 7, 1, 3, 4, 0, 0, 9],
    [0, 0, 9, 6, 0, 0, 0, 0, 5],
    [0, 3, 0, 0, 2, 0, 0, 8, 0]
]))

In [26]:
assert np.array_equal(board.arr, expected)

##### 2) Test: get rows

In [27]:
board = Board(puzzle_str)

In [28]:
assert np.array_equal(board.get_row(2), np.array([6, 0, 0, 4, 5, 3, 9, 7, 0]))

##### 3) Test: get columns

In [29]:
assert np.array_equal(board.get_column(4), np.array([8, 0, 5, 0, 0, 0, 3, 0, 2]))

##### 4) Test: get blocks

In [30]:
assert np.array_equal(board.get_block(1, 2), np.array([
    [0, 9, 0],
    [6, 0, 0],
    [0, 0, 0]
]))

In [31]:
assert np.array_equal(board.get_block(2, 2), np.array([
    [0, 0, 9],
    [0, 0, 5],
    [0, 8, 0]
]))

##### 5) Test: iter_rows()

In [32]:
assert np.array_equal(np.array(board.iter_rows()), np.array([
 np.array([0, 2, 0, 0, 8, 0, 0, 5, 0]),
 np.array([4, 0, 0, 0, 0, 6, 8, 0, 0]),
 np.array([6, 0, 0, 4, 5, 3, 9, 7, 0]),
 np.array([0, 0, 0, 0, 0, 2, 0, 9, 0]),
 np.array([0, 0, 4, 0, 0, 0, 6, 0, 0]),
 np.array([0, 1, 0, 3, 0, 0, 0, 0, 0]),
 np.array([0, 5, 7, 1, 3, 4, 0, 0, 9]),
 np.array([0, 0, 9, 6, 0, 0, 0, 0, 5]),
 np.array([0, 3, 0, 0, 2, 0, 0, 8, 0])]))

##### 6) Test: iter_columns()

In [33]:
assert np.array_equal(np.array(board.iter_columns()), np.array([
 np.array([0, 4, 6, 0, 0, 0, 0, 0, 0]),
 np.array([2, 0, 0, 0, 0, 1, 5, 0, 3]),
 np.array([0, 0, 0, 0, 4, 0, 7, 9, 0]),
 np.array([0, 0, 4, 0, 0, 3, 1, 6, 0]),
 np.array([8, 0, 5, 0, 0, 0, 3, 0, 2]),
 np.array([0, 6, 3, 2, 0, 0, 4, 0, 0]),
 np.array([0, 8, 9, 0, 6, 0, 0, 0, 0]),
 np.array([5, 0, 7, 9, 0, 0, 0, 0, 8]),
 np.array([0, 0, 0, 0, 0, 0, 9, 5, 0])]))

## Ready to move on?

Now copy your `Board` class into the file `sudoku.py`, we'll be using it in our next steps. Once you're ready, you can try running the tests using:


In [36]:
with open('test_part_1.py', 'w') as f:
    f.write('''
def test_example():
    assert 1 + 1 == 2
''')


In [37]:
!pytest test_part_1.py


======================================= test session starts ========================================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.5.0
rootdir: /content
plugins: typeguard-4.3.0, anyio-3.7.1
collected 1 item                                                                                   

test_part_1.py .                                                                             [100%]

======================================== 1 passed in 0.01s =========================================


Now head to Part 2! `2. Sudoku Validity.ipynb`.